# Generated by Django 5.0.6 on 2024-06-23 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Aadhar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("aadhar_no", models.CharField(max_length=14)),
                ("name", models.CharField(max_length=100)),
                ("gender", models.CharField(max_length=10)),
                ("dob", models.CharField(max_length=10)),
            ],
        ),
    ]
